name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Jest 
        run: npm install --save-dev jest 

      - name: Install Babel
        run: @babel/core @babel/preset-env @babel/preset-typescript @babel/preset-react @babel/plugin-transform-runtime

      - name: Install Testing Library for React
        run: npm install --save-dev @testing-library/react

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Check code style
        run: npm run lint

      - name: Check type errors
        run: npm run type-check
